return function()
    return {
        Players = game:GetService("Players"),
        RunService = game:GetService("RunService"),
        TweenService = game:GetService("TweenService"),
        HttpService = game:GetService("HttpService"),
        ReplicatedStorage = game:GetService("ReplicatedStorage"),
        Workspace = game:GetService("Workspace"),
        Lighting = game:GetService("Lighting"),
        TeleportService = game:GetService("TeleportService"),
        UserInputService = game:GetService("UserInputService"),
        VirtualUser = game:GetService("VirtualUser"),
        CoreGui = game:GetService("CoreGui"),
    }
end
